---
title: "background.rmd"
author: "Shane Connuck"
date: "2022-10-06"
output: html_document
---
I want to pursue the question about the Nets. While it seems tougher, I think it's just as doable. There were 16 games in which those three players — Kevin Durant, Kyrie Irving and James Harden — were all healthy and played. The Nets went 13-3 in those games, but didn't finish a season higher than the Eastern Conference's No. 2 seed in the regular season, before choking the Bucks in a seven-game series when those guys got hurt. How many more points would the Nets put up with those three compared to the rest of the team? How much more of an impact was it for the Nets to have Kyrie Irving playing instead of Bruce Brown?

I found the Brooklyn Nets' 2020-21 stats on Basketball Reference, but I'm unsure how to get those from the website into RStudio. From there, I would need to filter the data to show games where all three of them played, and then I would compare it to games they played with two of them, one, and when none of their stars suited up.

There has been a lot of talk about how the pretty much failed experiment of the "Big Three" went, and I want to dive into the impact they had and the classic "What could have been."